# Generated by Django 5.1.1 on 2024-09-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomor_ponsel', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('lokasi', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis_lomba', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('no_hp', models.CharField(max_length=13, unique=True)),
                ('alamat', models.CharField(max_length=255)),
                ('lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='lomba.lomba')),
            ],
        ),
    ]
